# Generated by Django 4.1.4 on 2022-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custNo", models.CharField(max_length=150)),
                ("bill_ym", models.CharField(max_length=150)),
                ("mr_ymd", models.CharField(max_length=150)),
                ("bill_aply_pwr", models.CharField(max_length=150)),
                ("move_ymd", models.CharField(max_length=150)),
                ("base_bill", models.CharField(max_length=150)),
                ("kwh_bill", models.CharField(max_length=150)),
                ("dc_bill", models.CharField(max_length=150)),
                ("req_bill", models.CharField(max_length=150)),
                ("req_amt", models.CharField(max_length=150)),
                ("lload_usekwh", models.CharField(max_length=150)),
                ("mload_usekwh", models.CharField(max_length=150)),
                ("maxload_usekwh", models.CharField(max_length=150)),
                ("lload_needle", models.CharField(max_length=150)),
                ("mload_needle", models.CharField(max_length=150)),
                ("maxload_needle", models.CharField(max_length=150)),
                ("jn_pwrfact", models.CharField(max_length=150)),
                ("ji_pwrfact", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
