# Generated by Django 4.1.4 on 2023-01-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="호실")),
                ("start", models.DateField(verbose_name="시작일")),
                ("end", models.DateField(verbose_name="종료일")),
                ("area", models.IntegerField(verbose_name="평형")),
                ("area_fee", models.IntegerField(verbose_name="평당 관리비")),
                ("deposit", models.IntegerField(verbose_name="보증금")),
                ("rent", models.IntegerField(verbose_name="월세")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="계약자 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "계약서",
                "verbose_name_plural": "계약서",
            },
        ),
    ]
