# Generated by Django 4.0.8 on 2023-03-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payed_cnt', models.PositiveIntegerField()),
                ('usage_end', models.DateField()),
                ('check_date', models.DateField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='contracts.contract')),
            ],
            options={
                'verbose_name': '월납입금',
                'verbose_name_plural': '월납입금 목록',
            },
        ),
    ]
