# Generated by Django 4.0.8 on 2023-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_payed',
        ),
    ]
