# Generated by Django 4.0.8 on 2023-03-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_rent_is_payed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': '납부회차', 'verbose_name_plural': '월납입금 목록'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='contracts.contract', verbose_name='계약서'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='payed_cnt',
            field=models.PositiveIntegerField(verbose_name='회차'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='usage_end',
            field=models.DateField(verbose_name='납기일'),
        ),
    ]
