# Generated by Django 4.1.4 on 2023-01-11 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_issue", models.BooleanField(default=False, verbose_name="발행여부")),
                (
                    "ratio",
                    models.FloatField(
                        help_text="발행시 계산합니다.", null=True, verbose_name="소실율"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "bill_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="청구일"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        help_text="상가 전체에 해당하는 전기료 청구금액의 합계", verbose_name="총청구금액"
                    ),
                ),
                (
                    "maintanance",
                    models.PositiveIntegerField(
                        help_text="상가 관리단 전기료의 합계", verbose_name="관리실금액"
                    ),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        help_text="부가세가 포함된 4층 전기료 청구요금", verbose_name="한전 청구요금"
                    ),
                ),
                (
                    "basic",
                    models.PositiveIntegerField(
                        help_text="적용요금에 따른 기본 요금", verbose_name="한전 기본요금"
                    ),
                ),
                (
                    "usage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="청구서에 기재된 전력사용량",
                        verbose_name="당월 사용량(kw)",
                    ),
                ),
                (
                    "usage_sum",
                    models.PositiveIntegerField(null=True, verbose_name="사용자 검침량 총합"),
                ),
                ("area_sum", models.PositiveIntegerField(verbose_name="임대면적 합계")),
                ("public_share", models.PositiveIntegerField(verbose_name="공용 기본전기료")),
                ("public_usage", models.PositiveIntegerField(verbose_name="공용 사용전기료")),
                ("total_public", models.PositiveIntegerField(verbose_name="공용전기료 총합")),
                ("none_tax", models.PositiveIntegerField(verbose_name="세전 사용량 전기료")),
                ("unit_price", models.PositiveIntegerField(verbose_name="단위당 단가")),
            ],
            options={
                "verbose_name": "청구서",
                "verbose_name_plural": "1. 청구서 입력",
            },
        ),
        migrations.CreateModel(
            name="OwnerCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, verbose_name="항목")),
                ("charge", models.IntegerField(verbose_name="비용")),
            ],
            options={
                "verbose_name": "부담내역",
                "verbose_name_plural": "임대인 부담",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_payed", models.BooleanField(default=False, verbose_name="입금여부")),
                (
                    "usage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="검침량"
                    ),
                ),
                ("public_share", models.PositiveIntegerField(verbose_name="공용 기본전기료")),
                ("area_fee", models.PositiveIntegerField(verbose_name="기본관리비")),
                ("basic", models.PositiveIntegerField(verbose_name="기본전기료")),
                (
                    "ratio_usage",
                    models.PositiveIntegerField(null=True, verbose_name="전력사용량"),
                ),
                (
                    "add_unit",
                    models.PositiveIntegerField(null=True, verbose_name="전력사용요금"),
                ),
                (
                    "without_tax",
                    models.PositiveIntegerField(null=True, verbose_name="전기요금"),
                ),
                ("tax", models.PositiveIntegerField(null=True, verbose_name="부가세")),
                (
                    "add_tax",
                    models.PositiveIntegerField(null=True, verbose_name="사용자 합계"),
                ),
                (
                    "public_usage",
                    models.PositiveIntegerField(null=True, verbose_name="공용 전력사용요금"),
                ),
                (
                    "public",
                    models.PositiveIntegerField(null=True, verbose_name="공용 합계"),
                ),
                ("total", models.PositiveIntegerField(null=True, verbose_name="총합")),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="bills.bill",
                        verbose_name="당월 청구서 정보",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                        verbose_name="계약자 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "인보이스",
                "verbose_name_plural": "2. 인보이스",
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="owner_charge",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="bills",
                to="bills.ownercharge",
                verbose_name="임대인 부담",
            ),
        ),
    ]
