# Generated by Django 4.1.4 on 2022-12-30 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="청구일"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        help_text="상가 총청구금액을 입력하세요.", verbose_name="총청구금액"
                    ),
                ),
                (
                    "maintanance",
                    models.PositiveIntegerField(
                        help_text="상가 관리단금액을 입력하세요.", verbose_name="관리실금액"
                    ),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        help_text="부가세가 포함된 청구요금을 입력하세요.", verbose_name="한전 청구요금"
                    ),
                ),
                (
                    "usage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="청구서에 기재된 전력사용량을 입력하세요.",
                        verbose_name="당월 사용량(kw)",
                    ),
                ),
            ],
            options={
                "verbose_name": "청구서",
                "verbose_name_plural": "1. 청구서 입력",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_issue", models.BooleanField(default=False, verbose_name="발행여부")),
                (
                    "issue_date",
                    models.DateField(
                        default=datetime.datetime(
                            2022,
                            12,
                            30,
                            6,
                            13,
                            45,
                            433758,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="발행일",
                    ),
                ),
                (
                    "usage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="호실별 검침량을 입력해주세요.",
                        null=True,
                        verbose_name="호실별 사용량",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="bills.bill",
                        verbose_name="청구서 정보",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="contracts.contract",
                        verbose_name="계약자 정보",
                    ),
                ),
            ],
            options={
                "verbose_name": "인보이스",
                "verbose_name_plural": "2. 인보이스",
            },
        ),
    ]
