# Generated by Django 4.1.4 on 2023-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="owner_charge",
            field=models.ManyToManyField(
                blank=True,
                related_name="bills",
                to="bills.ownercharge",
                verbose_name="임대인 부담",
            ),
        ),
    ]
