# Generated by Django 4.1.4 on 2022-12-30 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="발행일"
            ),
        ),
    ]
