# Generated by Django 4.1.4 on 2022-12-30 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_alter_invoice_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=datetime.date(2022, 12, 30), verbose_name="발행일"
            ),
        ),
    ]
