# Generated by Django 4.1.4 on 2022-12-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0004_alter_invoice_issue_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="issue_date",
        ),
    ]
