# Generated by Django 4.1.4 on 2022-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_remove_invoice_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="area_sum",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
