# Generated by Django 4.1.4 on 2022-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0006_bill_area_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="basic",
            field=models.PositiveIntegerField(
                default=0, help_text="기본 요금을 입력하세요.", verbose_name="한전 기본요금"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="area_sum",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="해당층 면적"
            ),
        ),
    ]
