# Generated by Django 4.1.4 on 2023-01-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0007_bill_basic_alter_bill_area_sum"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="area_cnt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
