# Generated by Django 4.1.4 on 2023-01-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0008_bill_area_cnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="basic",
            field=models.PositiveIntegerField(
                default=0, help_text="적용요금에 따른 기본 요금", verbose_name="한전 기본요금"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="floor",
            field=models.PositiveIntegerField(
                help_text="부가세가 포함된 4층 전기료 청구요금", verbose_name="한전 청구요금"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="usage",
            field=models.PositiveIntegerField(
                blank=True, help_text="청구서에 기재된 전력사용량", verbose_name="당월 사용량(kw)"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="bills.bill",
                verbose_name="전체 청구서 정보",
            ),
        ),
    ]
