# Generated by Django 4.1.4 on 2023-01-26 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=12, verbose_name="구분")),
                ("custNum", models.CharField(max_length=10, verbose_name="고객번호")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="비고"),
                ),
            ],
            options={
                "verbose_name": "고객번호정보",
                "verbose_name_plural": "고백번호 데이터 목록",
            },
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bill_ym", models.CharField(max_length=6, verbose_name="청구년월")),
                ("mr_ymd", models.CharField(max_length=2, verbose_name="정기검침일")),
                (
                    "bill_aply_pwr",
                    models.CharField(max_length=15, verbose_name="요금적용전력"),
                ),
                ("move_ymd", models.CharField(max_length=8, verbose_name="이사정산일")),
                ("base_bill", models.CharField(max_length=17, verbose_name="기본요금")),
                ("kwh_bill", models.CharField(max_length=17, verbose_name="전력량요금")),
                ("dc_bill", models.CharField(max_length=15, verbose_name="할인")),
                ("req_bill", models.CharField(max_length=15, verbose_name="전기요금계")),
                ("req_amt", models.CharField(max_length=15, verbose_name="청구요금")),
                (
                    "lload_usekwh",
                    models.CharField(max_length=15, verbose_name="경부하사용량"),
                ),
                (
                    "mload_usekwh",
                    models.CharField(max_length=15, verbose_name="중부하사용량"),
                ),
                (
                    "maxload_usekwh",
                    models.CharField(max_length=15, verbose_name="최대부하사용량"),
                ),
                (
                    "lload_needle",
                    models.CharField(max_length=15, verbose_name="경부하당월지침"),
                ),
                (
                    "mload_needle",
                    models.CharField(max_length=15, verbose_name="중부하당월지침"),
                ),
                (
                    "maxload_needle",
                    models.CharField(max_length=15, verbose_name="최대부하당월지침"),
                ),
                ("jn_pwrfact", models.CharField(max_length=6, verbose_name="진상역률")),
                ("ji_pwrfact", models.CharField(max_length=6, verbose_name="지상역률")),
                (
                    "custNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="informations.customer",
                        verbose_name="고객번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객청구정보",
                "verbose_name_plural": "고객청구정보 데이터 목록",
            },
        ),
    ]
