# Generated by Django 4.0.8 on 2023-03-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금')], max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': '회계내역',
                'verbose_name_plural': '회계내역 목록',
            },
        ),
    ]
