# Generated by Django 4.0.8 on 2023-03-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_accounting_obligor_alter_accounting_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accounting',
            name='kind',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('replacement', '갈음')], max_length=12),
        ),
    ]
