# Generated by Django 4.0.8 on 2023-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_conciergeduty_alter_accounting_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciergeduty',
            options={'verbose_name': '대납', 'verbose_name_plural': '대납 목록'},
        ),
        migrations.AlterField(
            model_name='accounting',
            name='kind',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금'), ('replacement', '갈음'), ('concierge', '대납')], max_length=12),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='obligor',
            field=models.CharField(choices=[('owner', '임대인'), ('lessee', '임차인')], default='owner', max_length=10),
        ),
    ]
