# Generated by Django 4.0.8 on 2023-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_alter_conciergeduty_options_alter_accounting_kind_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConciergeDuty',
        ),
        migrations.RemoveField(
            model_name='accounting',
            name='obligor',
        ),
        migrations.AlterField(
            model_name='accounting',
            name='kind',
            field=models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금')], max_length=10),
        ),
    ]
