# Generated by Django 4.0.8 on 2023-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': '메시지', 'verbose_name_plural': 'SMS'},
        ),
    ]
