# Generated by Django 4.0.8 on 2023-03-17 09:41

from django.db import migrations, models
import messengers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0002_alter_sms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendLMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=120)),
                ('contents', models.TextField(validators=[messengers.validators.validate_binary_lms])),
                ('phone_number', models.CharField(max_length=11)),
                ('sended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
