# Generated by Django 4.0.8 on 2023-03-17 09:50

from django.db import migrations, models
import messengers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0003_sendlms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlms',
            name='created_at',
            field=models.DateTimeField(validators=[messengers.validators.validate_count_lms]),
        ),
    ]
