# Generated by Django 4.0.8 on 2023-03-23 07:38

from django.db import migrations, models
import messengers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0004_alter_sendlms_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlms',
            options={'verbose_name': '메시지 발송', 'verbose_name_plural': 'LMS'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': '메시지', 'verbose_name_plural': '미납요금 SMS 목록'},
        ),
        migrations.AlterField(
            model_name='sendlms',
            name='contents',
            field=models.TextField(help_text='최대 2000바이트', validators=[messengers.validators.validate_binary_lms], verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='sendlms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, validators=[messengers.validators.validate_count_lms], verbose_name='발송시간'),
        ),
        migrations.AlterField(
            model_name='sendlms',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='수신번호'),
        ),
        migrations.AlterField(
            model_name='sendlms',
            name='sended',
            field=models.BooleanField(default=False, editable=False, verbose_name='발신여부'),
        ),
        migrations.AlterField(
            model_name='sendlms',
            name='subject',
            field=models.CharField(help_text='최대 30자', max_length=30, validators=[messengers.validators.validate_binary_subject], verbose_name='제목'),
        ),
    ]
