# Generated by Django 4.0.8 on 2023-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherfcst',
            name='base_date',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='weatherfcst',
            name='base_time',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
