# Generated by Django 4.0.8 on 2023-03-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimes', '0002_weatherfcst_base_date_weatherfcst_base_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherfcst',
            old_name='base_date',
            new_name='baseDate',
        ),
        migrations.RenameField(
            model_name='weatherfcst',
            old_name='base_time',
            new_name='baseTime',
        ),
    ]
