# Generated by Django 4.0.8 on 2023-03-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimes', '0003_rename_base_date_weatherfcst_basedate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherfcst',
            options={'verbose_name': '날씨', 'verbose_name_plural': '초단기예보'},
        ),
    ]
